### ISSUE TITLE
Need help Raspberry pi

### ISSUE THREAD

**Issue by nelsonalejandro** [QuickGroup/pyGT511C3#3]
Hi,
I Need help to run this in raspberry pi.

:)

**Comment by JordiSapesPlanas** [comment]
Hola buenas, yo tambien estoy probando el lector (en este caso el GT511C1R) y nose como debo conectar los cables a los pines de la rasberry. He logrado que se me quedara el led encendido y apagarlo. Pero nunca recibo nada del lector. Me podrian decir como y que necessito para poder probar el driver en python? 

Muchas gracias

**Comment by jeanmachuca** [comment]
Hola, 

Este driver está diseñado para el GT511C3 pero hay personas que lo han probado con el GT511C1 sin problemas. 

Si quieres puedes usar el test de ejemplo para raspberry pi 

https://github.com/QuickGroup/pyGT511C3/blob/master/raspberry_pi_GPIO_test.py

Debes conectar los pines TX y RX cruzados, es decir, el TX del dispositivo en el RX del GPIO, y viceversa. VCC y GND van en línea

Si tienes problemas para recibir la respuesta de los comandos tal vez tienes que ajustar el parámetro que va en las llamadas a FPS.delay() 

Mucha suerte y nos cuentas el resultado!

**Comment by JordiSapesPlanas** [comment]
Hola de nuevo, y gracias por la rapida respuesta. 

He conectado el pin1(el del  mas a la izquierda con el lector mirando haciua arriba) con el pin RX de la rasberry. El pin2 (del media a la izquierda) con el pin TX de la rasberry. El pin3 ( pin del medio a la derecha) con el pin GND de la rasberry i finalmente el de la derecha con el pin 3,3 V de la rasberry.

Siguiendo el datasheet del fingerPrint GT511C3 seria la conexion conecta siguiendo los pasos que me habeis conectado. ( en el datashet del fingrePrint GT511C1R no queda muy claro https://cdn.sparkfun.com/datasheets/Sensors/Biometric/GT-511C1R_datasheet_V1%205_20140312.pdf)

La salida que me da al ejecutar rasberry_pi_GPIO_test.py es:

Command: Open
55 aa 01 00 01 00 00 00 01 00 02 01
U\AA\00\00\00\00\00
U\xaa\x01\x00\x01\x00\x00\x00\x01\x00\x02\x01
readed: 
Command: CmosLed
55 aa 01 00 01 00 00 00 12 00 13 01
U\AA\00\00\00\00\00
U\xaa\x01\x00\x01\x00\x00\x00\x12\x00\x13\x01
readed: 
Put your finger in the scan
Command: IsPressFinger
55 aa 01 00 01 00 00 00 26 00 27 01
U\AA\00\00\00\00&\00'
U\xaa\x01\x00\x01\x00\x00\x00&\x00'\x01
readed: 
Your finger is in the scan
Command: CmosLed
55 aa 01 00 00 00 00 00 12 00 12 01
U\AA\00\00\00\00\00\00
U\xaa\x01\x00\x00\x00\x00\x00\x12\x00\x12\x01
readed: 
Command: Close
55 aa 01 00 00 00 00 00 02 00 02 01
U\AA\00\00\00\00\00\00
U\xaa\x01\x00\x00\x00\x00\x00\x02\x00\x02\x01
readed: 

No lee nada... Y el lector tampoco da ninguna senyal de vida... 
Cuando tengo los cables conectados... El lector deberia tener alguna luz encendida? En el caso del lector C3 como actua cuando esta conectado y cuando recive los bytes? 
Muchas gracias

**Comment by jeanmachuca** [comment]
El lector no enciende ninguna luz, el led se enciende y se apaga con un comando.
Si tienes todo conectado y no recibes respuesta puede ser por 2 cosas:

1.- Tienes los pines TX y RX invertidos. Prueba cambiando los pines y ejecuta el test nuevamente
2.- El baudrate del dispositivo no es el mismo que el del GPIO.  ejecuta el archivo baud_to_115200.py
(https://github.com/QuickGroup/pyGT511C3/blob/master/baud_to_115200.py). Esto cambiará la frecuencia del dispositivo permanentemente a 115200

**Comment by JordiSapesPlanas** [comment]
Hola de nuevo, el problema que tenia no era un problema ni del baudrate ni de los pines que conectava. Tenia un problema con el conector. El cable GND no hacia buen contacto en el conector y por ese motivo no recibia nunca la senyal. Muchas gracias por la ayuda!

**Comment by jeanmachuca** [comment]
Ok

**Comment by matias-94** [comment]
hola, estoy trabajando con un modulo ESP8266 (nodemcu) y GT511c3.
gracias a la información anterior puedo encender, apagar el LED . 
dejo mi ejemplo:
encender = string.char(0x55,0xAA,0x01,0x00,0x01,0x00,0x00,0x00,0x12,0x00,0x13,0x01)
uart.write(0, encender)

mi duda es sobre los parámetros, se que son 4 pero no se que información debo poner y en cual de los 4 debe ser? agradezco de ante mano la ayuda.

**Comment by jeanmachuca** [comment]
Please see the ParameterFromInt() AND IntFromParameter() methods in FPS.py

**Comment by matias-94** [comment]
gracias, esto es lo que necesito ParameterFromInt():
conozco muy poco el lenguaje python, si pudieras explicarme que hacen estas lineas te lo agradecería mucho. 
self.Parameter[0] = (i & 0x000000ff);
self.Parameter[1] = (i & 0x0000ff00) >> 8;
self.Parameter[2] = (i & 0x00ff0000) >> 16;
self.Parameter[3] = (i & 0xff000000) >> 24;

ya que estoy adaptando partes del código al modulo ESP8266. Que utiliza el lenguaje de programación LUA.

**Comment by jeanmachuca** [comment]
Please RTF :D 
https://wiki.python.org/moin/BitwiseOperators

**Comment by matias-94** [comment]
thank you :D eso necesitaba...

**Comment by matias-94** [comment]
una pregunta en los parametros solo tengo que poner numero?
para utilizar cualquier otro comando solo cargo 1 como parametro?

pd: eh estado adaptando el codigo al lenguaje de programacion lua :D

**Comment by nicmuka** [comment]
Hi, I need to copy a fingerprint template and store it in a different database but I really understand how to use the data packet in Settemplate() and Gettemplate(). Please help.

**Comment by nicmuka** [comment]
Also for your license. Can anybody add or modify FPS.py? I have more than 200 user and I need to use another database, reason why i need the DATA Packet.
