### ISSUE TITLE
Proyecto

### ISSUE THREAD

**Issue by nelsonalejandro** [QuickGroup/pyGT511C3#9]
adjunto mi proyecto de titulo para que puedan realizar todo lo que quieran con el sistema que programe.

SALUDOS.

https://www.dropbox.com/s/2g66jf2k4k5q56u/Proyecto%20de%20Titulo.rar?dl=0

**Comment by jeanmachuca** [comment]
Muchas gracias por compartir, puedes subir tu código a github y hacer fork a este proyecto, recuerda hacer referencia al uso de la librería pyGT511C3 y mantenter la copia del archivo de licencia LICENSE.txt al igual que los comentarios de autor del código fuente
